// <auto-generated />
using System;
using HotChocolate.Checker.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotChocolate.Checker.Migrations
{
    [DbContext(typeof(CheckerDbContext))]
    [Migration("20230706191552_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Genre = "Latin",
                            ISBN = "2578066949413",
                            Language = "Research",
                            PageCount = 8461,
                            PublicationDate = new DateTime(2022, 10, 22, 5, 50, 9, 98, DateTimeKind.Local).AddTicks(5870),
                            Title = "Koch Inc"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Genre = "Blues",
                            ISBN = "6080081688483",
                            Language = "Wisconsin",
                            PageCount = 1678,
                            PublicationDate = new DateTime(2022, 12, 7, 16, 50, 27, 677, DateTimeKind.Local).AddTicks(7000),
                            Title = "Armstrong - Wolf"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Genre = "Funk",
                            ISBN = "2198401616918",
                            Language = "back-end",
                            PageCount = 278,
                            PublicationDate = new DateTime(2022, 7, 27, 7, 0, 53, 163, DateTimeKind.Local).AddTicks(9715),
                            Title = "Sanford, Marquardt and Buckridge"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Genre = "Pop",
                            ISBN = "9709776571240",
                            Language = "generate",
                            PageCount = 1360,
                            PublicationDate = new DateTime(2023, 6, 23, 22, 46, 44, 159, DateTimeKind.Local).AddTicks(5832),
                            Title = "Feil LLC"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            Genre = "Soul",
                            ISBN = "0706326643951",
                            Language = "Grass-roots",
                            PageCount = 7214,
                            PublicationDate = new DateTime(2022, 7, 12, 9, 27, 35, 728, DateTimeKind.Local).AddTicks(9573),
                            Title = "Lowe - Mann"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            Genre = "Stage And Screen",
                            ISBN = "8874111695644",
                            Language = "Mandatory",
                            PageCount = 8879,
                            PublicationDate = new DateTime(2023, 3, 4, 12, 54, 13, 562, DateTimeKind.Local).AddTicks(7074),
                            Title = "Ullrich Inc"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            Genre = "Rap",
                            ISBN = "3579108222142",
                            Language = "initiative",
                            PageCount = 5361,
                            PublicationDate = new DateTime(2023, 7, 4, 23, 18, 38, 552, DateTimeKind.Local).AddTicks(2257),
                            Title = "VonRueden Group"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            Genre = "Rock",
                            ISBN = "7557348716566",
                            Language = "Vatu",
                            PageCount = 2704,
                            PublicationDate = new DateTime(2023, 3, 7, 1, 22, 18, 597, DateTimeKind.Local).AddTicks(7827),
                            Title = "Wolf, Crona and Dickens"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            Genre = "Non Music",
                            ISBN = "9914130873537",
                            Language = "Identity",
                            PageCount = 1881,
                            PublicationDate = new DateTime(2022, 8, 28, 4, 35, 44, 22, DateTimeKind.Local).AddTicks(5784),
                            Title = "Block and Sons"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            Genre = "Blues",
                            ISBN = "2122528039480",
                            Language = "methodologies",
                            PageCount = 1350,
                            PublicationDate = new DateTime(2022, 12, 27, 23, 27, 55, 60, DateTimeKind.Local).AddTicks(8535),
                            Title = "Mueller LLC"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 11,
                            Genre = "Pop",
                            ISBN = "5850767118907",
                            Language = "Handmade Wooden Towels",
                            PageCount = 7336,
                            PublicationDate = new DateTime(2022, 10, 26, 22, 57, 8, 146, DateTimeKind.Local).AddTicks(1247),
                            Title = "Bernhard, Ledner and Breitenberg"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 12,
                            Genre = "Hip Hop",
                            ISBN = "7683554599805",
                            Language = "British Indian Ocean Territory (Chagos Archipelago)",
                            PageCount = 9709,
                            PublicationDate = new DateTime(2023, 1, 6, 22, 48, 15, 511, DateTimeKind.Local).AddTicks(9050),
                            Title = "Borer - Mayert"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 13,
                            Genre = "Country",
                            ISBN = "0939926533128",
                            Language = "Trail",
                            PageCount = 5923,
                            PublicationDate = new DateTime(2023, 6, 5, 8, 41, 4, 578, DateTimeKind.Local).AddTicks(7377),
                            Title = "Simonis - Dickinson"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 14,
                            Genre = "Non Music",
                            ISBN = "9803219960643",
                            Language = "Unbranded Frozen Hat",
                            PageCount = 7260,
                            PublicationDate = new DateTime(2022, 11, 12, 8, 45, 49, 427, DateTimeKind.Local).AddTicks(2315),
                            Title = "Wilkinson, Dicki and Blick"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 15,
                            Genre = "Jazz",
                            ISBN = "0795044075762",
                            Language = "bypassing",
                            PageCount = 3498,
                            PublicationDate = new DateTime(2022, 9, 24, 3, 51, 50, 38, DateTimeKind.Local).AddTicks(2694),
                            Title = "Herman - MacGyver"
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 16,
                            Genre = "Non Music",
                            ISBN = "8808016471928",
                            Language = "sexy",
                            PageCount = 3660,
                            PublicationDate = new DateTime(2023, 1, 17, 7, 41, 6, 800, DateTimeKind.Local).AddTicks(7912),
                            Title = "Parisian Inc"
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 17,
                            Genre = "Non Music",
                            ISBN = "9156355425430",
                            Language = "Customer",
                            PageCount = 2037,
                            PublicationDate = new DateTime(2022, 8, 23, 22, 48, 36, 335, DateTimeKind.Local).AddTicks(9384),
                            Title = "Welch LLC"
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 18,
                            Genre = "Metal",
                            ISBN = "8755236184834",
                            Language = "Handcrafted Frozen Gloves",
                            PageCount = 1480,
                            PublicationDate = new DateTime(2023, 3, 11, 7, 48, 38, 727, DateTimeKind.Local).AddTicks(3702),
                            Title = "Aufderhar - Erdman"
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 19,
                            Genre = "Funk",
                            ISBN = "9688358714766",
                            Language = "grey",
                            PageCount = 2076,
                            PublicationDate = new DateTime(2022, 7, 23, 13, 58, 42, 459, DateTimeKind.Local).AddTicks(778),
                            Title = "Metz Group"
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 20,
                            Genre = "Rock",
                            ISBN = "5648646388356",
                            Language = "Canada",
                            PageCount = 6547,
                            PublicationDate = new DateTime(2023, 5, 1, 12, 11, 8, 70, DateTimeKind.Local).AddTicks(8560),
                            Title = "Emmerich LLC"
                        },
                        new
                        {
                            Id = 21,
                            AuthorId = 21,
                            Genre = "Stage And Screen",
                            ISBN = "8706719727499",
                            Language = "e-enable",
                            PageCount = 3277,
                            PublicationDate = new DateTime(2022, 8, 21, 0, 42, 24, 962, DateTimeKind.Local).AddTicks(6994),
                            Title = "Hackett - Gleason"
                        },
                        new
                        {
                            Id = 22,
                            AuthorId = 22,
                            Genre = "World",
                            ISBN = "1093955065902",
                            Language = "Chief",
                            PageCount = 8551,
                            PublicationDate = new DateTime(2023, 2, 7, 0, 7, 35, 991, DateTimeKind.Local).AddTicks(4652),
                            Title = "Lind - Ward"
                        },
                        new
                        {
                            Id = 23,
                            AuthorId = 23,
                            Genre = "Folk",
                            ISBN = "4178294105643",
                            Language = "calculate",
                            PageCount = 8112,
                            PublicationDate = new DateTime(2022, 12, 31, 17, 2, 52, 806, DateTimeKind.Local).AddTicks(1927),
                            Title = "Murphy - Beahan"
                        },
                        new
                        {
                            Id = 24,
                            AuthorId = 24,
                            Genre = "Rap",
                            ISBN = "1521207064989",
                            Language = "Saint Kitts and Nevis",
                            PageCount = 6662,
                            PublicationDate = new DateTime(2023, 7, 2, 3, 40, 58, 391, DateTimeKind.Local).AddTicks(8509),
                            Title = "Prohaska, Murray and Nienow"
                        },
                        new
                        {
                            Id = 25,
                            AuthorId = 25,
                            Genre = "Pop",
                            ISBN = "7092145901611",
                            Language = "hack",
                            PageCount = 6825,
                            PublicationDate = new DateTime(2022, 7, 18, 6, 23, 47, 483, DateTimeKind.Local).AddTicks(9180),
                            Title = "Botsford - Will"
                        },
                        new
                        {
                            Id = 26,
                            AuthorId = 26,
                            Genre = "Country",
                            ISBN = "6162601546425",
                            Language = "integrate",
                            PageCount = 7293,
                            PublicationDate = new DateTime(2022, 11, 11, 19, 43, 0, 184, DateTimeKind.Local).AddTicks(4474),
                            Title = "Kutch and Sons"
                        },
                        new
                        {
                            Id = 27,
                            AuthorId = 27,
                            Genre = "Funk",
                            ISBN = "3526215834225",
                            Language = "Mobility",
                            PageCount = 3571,
                            PublicationDate = new DateTime(2023, 3, 27, 8, 1, 30, 262, DateTimeKind.Local).AddTicks(8732),
                            Title = "Fisher and Sons"
                        },
                        new
                        {
                            Id = 28,
                            AuthorId = 28,
                            Genre = "Latin",
                            ISBN = "5412671905280",
                            Language = "Peso Uruguayo",
                            PageCount = 7602,
                            PublicationDate = new DateTime(2023, 4, 9, 1, 37, 14, 679, DateTimeKind.Local).AddTicks(6298),
                            Title = "Swaniawski - Leffler"
                        },
                        new
                        {
                            Id = 29,
                            AuthorId = 29,
                            Genre = "Country",
                            ISBN = "1527854874377",
                            Language = "Electronics",
                            PageCount = 2221,
                            PublicationDate = new DateTime(2023, 6, 3, 19, 2, 36, 779, DateTimeKind.Local).AddTicks(1553),
                            Title = "Koch - DuBuque"
                        },
                        new
                        {
                            Id = 30,
                            AuthorId = 30,
                            Genre = "Hip Hop",
                            ISBN = "2301627798003",
                            Language = "Diverse",
                            PageCount = 3444,
                            PublicationDate = new DateTime(2023, 1, 20, 10, 18, 43, 280, DateTimeKind.Local).AddTicks(9874),
                            Title = "Larson - Feil"
                        },
                        new
                        {
                            Id = 31,
                            AuthorId = 31,
                            Genre = "Rock",
                            ISBN = "6073973844067",
                            Language = "hierarchy",
                            PageCount = 8458,
                            PublicationDate = new DateTime(2023, 2, 25, 22, 47, 34, 345, DateTimeKind.Local).AddTicks(2465),
                            Title = "Torphy and Sons"
                        },
                        new
                        {
                            Id = 32,
                            AuthorId = 32,
                            Genre = "Rock",
                            ISBN = "7202473762338",
                            Language = "back up",
                            PageCount = 5238,
                            PublicationDate = new DateTime(2022, 11, 28, 1, 12, 11, 126, DateTimeKind.Local).AddTicks(3484),
                            Title = "Jenkins, Cartwright and Wiegand"
                        },
                        new
                        {
                            Id = 33,
                            AuthorId = 33,
                            Genre = "Jazz",
                            ISBN = "5306490763704",
                            Language = "Generic Wooden Bacon",
                            PageCount = 3909,
                            PublicationDate = new DateTime(2023, 5, 1, 6, 12, 13, 848, DateTimeKind.Local).AddTicks(4824),
                            Title = "Spinka - Dare"
                        },
                        new
                        {
                            Id = 34,
                            AuthorId = 34,
                            Genre = "Funk",
                            ISBN = "9900681554810",
                            Language = "Serbian Dinar",
                            PageCount = 8663,
                            PublicationDate = new DateTime(2023, 2, 8, 9, 7, 47, 360, DateTimeKind.Local).AddTicks(8063),
                            Title = "Altenwerth and Sons"
                        },
                        new
                        {
                            Id = 35,
                            AuthorId = 35,
                            Genre = "Electronic",
                            ISBN = "3799817989154",
                            Language = "Texas",
                            PageCount = 801,
                            PublicationDate = new DateTime(2022, 10, 13, 11, 42, 42, 24, DateTimeKind.Local).AddTicks(4342),
                            Title = "Schmitt Group"
                        },
                        new
                        {
                            Id = 36,
                            AuthorId = 36,
                            Genre = "Non Music",
                            ISBN = "6409724237121",
                            Language = "back up",
                            PageCount = 9029,
                            PublicationDate = new DateTime(2023, 6, 26, 23, 9, 50, 565, DateTimeKind.Local).AddTicks(694),
                            Title = "Roberts Group"
                        },
                        new
                        {
                            Id = 37,
                            AuthorId = 37,
                            Genre = "Folk",
                            ISBN = "5440064373330",
                            Language = "Assistant",
                            PageCount = 873,
                            PublicationDate = new DateTime(2023, 3, 24, 3, 10, 56, 93, DateTimeKind.Local).AddTicks(726),
                            Title = "Bartoletti - Will"
                        },
                        new
                        {
                            Id = 38,
                            AuthorId = 38,
                            Genre = "Country",
                            ISBN = "5873924663416",
                            Language = "Money Market Account",
                            PageCount = 2248,
                            PublicationDate = new DateTime(2023, 3, 12, 11, 43, 29, 798, DateTimeKind.Local).AddTicks(4043),
                            Title = "Reilly, Dibbert and Wuckert"
                        },
                        new
                        {
                            Id = 39,
                            AuthorId = 39,
                            Genre = "Country",
                            ISBN = "5388238303922",
                            Language = "Jewelery & Books",
                            PageCount = 3259,
                            PublicationDate = new DateTime(2022, 10, 24, 10, 4, 1, 77, DateTimeKind.Local).AddTicks(8043),
                            Title = "Brown, Langosh and Gorczany"
                        },
                        new
                        {
                            Id = 40,
                            AuthorId = 40,
                            Genre = "Blues",
                            ISBN = "4574136044734",
                            Language = "Wall",
                            PageCount = 871,
                            PublicationDate = new DateTime(2023, 4, 11, 10, 34, 59, 497, DateTimeKind.Local).AddTicks(129),
                            Title = "Rogahn, Williamson and VonRueden"
                        },
                        new
                        {
                            Id = 41,
                            AuthorId = 41,
                            Genre = "Blues",
                            ISBN = "7181682455227",
                            Language = "pixel",
                            PageCount = 5181,
                            PublicationDate = new DateTime(2023, 5, 5, 3, 19, 17, 264, DateTimeKind.Local).AddTicks(8777),
                            Title = "Parisian, Reichel and Schmidt"
                        },
                        new
                        {
                            Id = 42,
                            AuthorId = 42,
                            Genre = "World",
                            ISBN = "1791282010588",
                            Language = "Research",
                            PageCount = 9682,
                            PublicationDate = new DateTime(2023, 4, 14, 18, 32, 11, 837, DateTimeKind.Local).AddTicks(9325),
                            Title = "Kautzer - Doyle"
                        },
                        new
                        {
                            Id = 43,
                            AuthorId = 43,
                            Genre = "Reggae",
                            ISBN = "2162881148870",
                            Language = "Saint Helena Pound",
                            PageCount = 2811,
                            PublicationDate = new DateTime(2022, 7, 16, 22, 16, 2, 435, DateTimeKind.Local).AddTicks(1554),
                            Title = "Hartmann, Goldner and Labadie"
                        },
                        new
                        {
                            Id = 44,
                            AuthorId = 44,
                            Genre = "Electronic",
                            ISBN = "2982568282020",
                            Language = "Sleek Wooden Gloves",
                            PageCount = 2323,
                            PublicationDate = new DateTime(2023, 7, 6, 18, 22, 15, 485, DateTimeKind.Local).AddTicks(7910),
                            Title = "Hamill Inc"
                        },
                        new
                        {
                            Id = 45,
                            AuthorId = 45,
                            Genre = "Classical",
                            ISBN = "1346460913870",
                            Language = "Business-focused",
                            PageCount = 4345,
                            PublicationDate = new DateTime(2022, 11, 21, 5, 11, 17, 266, DateTimeKind.Local).AddTicks(4086),
                            Title = "Dooley, Kuhn and Schimmel"
                        },
                        new
                        {
                            Id = 46,
                            AuthorId = 46,
                            Genre = "Stage And Screen",
                            ISBN = "8073488447478",
                            Language = "neural",
                            PageCount = 1364,
                            PublicationDate = new DateTime(2023, 7, 2, 1, 59, 45, 905, DateTimeKind.Local).AddTicks(871),
                            Title = "Mayer - Daniel"
                        },
                        new
                        {
                            Id = 47,
                            AuthorId = 47,
                            Genre = "World",
                            ISBN = "6021484205129",
                            Language = "help-desk",
                            PageCount = 8803,
                            PublicationDate = new DateTime(2022, 8, 24, 6, 31, 7, 159, DateTimeKind.Local).AddTicks(1179),
                            Title = "Denesik LLC"
                        },
                        new
                        {
                            Id = 48,
                            AuthorId = 48,
                            Genre = "Blues",
                            ISBN = "4840332721718",
                            Language = "deposit",
                            PageCount = 27,
                            PublicationDate = new DateTime(2023, 2, 13, 15, 43, 14, 47, DateTimeKind.Local).AddTicks(478),
                            Title = "Ratke LLC"
                        },
                        new
                        {
                            Id = 49,
                            AuthorId = 49,
                            Genre = "World",
                            ISBN = "4995979972075",
                            Language = "Licensed",
                            PageCount = 4130,
                            PublicationDate = new DateTime(2022, 7, 29, 19, 27, 10, 907, DateTimeKind.Local).AddTicks(7282),
                            Title = "Hermann, Murphy and Stiedemann"
                        },
                        new
                        {
                            Id = 50,
                            AuthorId = 50,
                            Genre = "Rap",
                            ISBN = "3383695458828",
                            Language = "synthesizing",
                            PageCount = 7652,
                            PublicationDate = new DateTime(2023, 3, 14, 20, 37, 24, 359, DateTimeKind.Local).AddTicks(2720),
                            Title = "Emmerich - Kunde"
                        },
                        new
                        {
                            Id = 51,
                            AuthorId = 51,
                            Genre = "Jazz",
                            ISBN = "8707165386834",
                            Language = "overriding",
                            PageCount = 8154,
                            PublicationDate = new DateTime(2022, 10, 8, 21, 13, 5, 646, DateTimeKind.Local).AddTicks(7684),
                            Title = "Bahringer Inc"
                        },
                        new
                        {
                            Id = 52,
                            AuthorId = 52,
                            Genre = "Reggae",
                            ISBN = "4027091618835",
                            Language = "tan",
                            PageCount = 215,
                            PublicationDate = new DateTime(2022, 11, 16, 7, 31, 58, 871, DateTimeKind.Local).AddTicks(4347),
                            Title = "Strosin - Leffler"
                        },
                        new
                        {
                            Id = 53,
                            AuthorId = 53,
                            Genre = "Blues",
                            ISBN = "3845576527387",
                            Language = "Versatile",
                            PageCount = 8869,
                            PublicationDate = new DateTime(2022, 12, 20, 16, 13, 11, 941, DateTimeKind.Local).AddTicks(2188),
                            Title = "Lebsack - Torp"
                        },
                        new
                        {
                            Id = 54,
                            AuthorId = 54,
                            Genre = "Country",
                            ISBN = "1377072073928",
                            Language = "Japan",
                            PageCount = 4842,
                            PublicationDate = new DateTime(2022, 7, 28, 10, 29, 38, 862, DateTimeKind.Local).AddTicks(9574),
                            Title = "Monahan - O'Connell"
                        },
                        new
                        {
                            Id = 55,
                            AuthorId = 55,
                            Genre = "Metal",
                            ISBN = "3202417408692",
                            Language = "Licensed Wooden Towels",
                            PageCount = 3599,
                            PublicationDate = new DateTime(2022, 7, 23, 1, 17, 44, 197, DateTimeKind.Local).AddTicks(8732),
                            Title = "Green Group"
                        },
                        new
                        {
                            Id = 56,
                            AuthorId = 56,
                            Genre = "Classical",
                            ISBN = "6090464601596",
                            Language = "Afghanistan",
                            PageCount = 8511,
                            PublicationDate = new DateTime(2022, 11, 2, 12, 24, 36, 46, DateTimeKind.Local).AddTicks(7375),
                            Title = "Kassulke - Green"
                        },
                        new
                        {
                            Id = 57,
                            AuthorId = 57,
                            Genre = "Stage And Screen",
                            ISBN = "0247948950992",
                            Language = "Savings Account",
                            PageCount = 4008,
                            PublicationDate = new DateTime(2022, 12, 8, 11, 54, 21, 874, DateTimeKind.Local).AddTicks(8997),
                            Title = "Boyle and Sons"
                        },
                        new
                        {
                            Id = 58,
                            AuthorId = 58,
                            Genre = "Folk",
                            ISBN = "5762760748503",
                            Language = "calculate",
                            PageCount = 6514,
                            PublicationDate = new DateTime(2022, 9, 27, 15, 28, 39, 986, DateTimeKind.Local).AddTicks(6813),
                            Title = "Sporer, Wolf and Gulgowski"
                        },
                        new
                        {
                            Id = 59,
                            AuthorId = 59,
                            Genre = "Classical",
                            ISBN = "2100442614884",
                            Language = "Ergonomic",
                            PageCount = 2687,
                            PublicationDate = new DateTime(2023, 2, 14, 11, 35, 12, 455, DateTimeKind.Local).AddTicks(9531),
                            Title = "Watsica - Kozey"
                        },
                        new
                        {
                            Id = 60,
                            AuthorId = 60,
                            Genre = "Pop",
                            ISBN = "6482218023851",
                            Language = "Awesome Plastic Computer",
                            PageCount = 7130,
                            PublicationDate = new DateTime(2022, 10, 10, 4, 14, 2, 272, DateTimeKind.Local).AddTicks(6585),
                            Title = "Balistreri Group"
                        },
                        new
                        {
                            Id = 61,
                            AuthorId = 61,
                            Genre = "Metal",
                            ISBN = "2115697920369",
                            Language = "methodology",
                            PageCount = 1472,
                            PublicationDate = new DateTime(2023, 6, 20, 4, 3, 41, 434, DateTimeKind.Local).AddTicks(2634),
                            Title = "Stracke, Bauch and Cruickshank"
                        },
                        new
                        {
                            Id = 62,
                            AuthorId = 62,
                            Genre = "Country",
                            ISBN = "7543393522351",
                            Language = "Cambridgeshire",
                            PageCount = 3053,
                            PublicationDate = new DateTime(2023, 6, 20, 3, 38, 25, 858, DateTimeKind.Local).AddTicks(5257),
                            Title = "Carroll LLC"
                        },
                        new
                        {
                            Id = 63,
                            AuthorId = 63,
                            Genre = "Rap",
                            ISBN = "2690825257758",
                            Language = "SDR",
                            PageCount = 893,
                            PublicationDate = new DateTime(2022, 9, 27, 8, 38, 50, 243, DateTimeKind.Local).AddTicks(8376),
                            Title = "Heidenreich, Oberbrunner and Nicolas"
                        },
                        new
                        {
                            Id = 64,
                            AuthorId = 64,
                            Genre = "Stage And Screen",
                            ISBN = "2686358190402",
                            Language = "Clothing & Sports",
                            PageCount = 4638,
                            PublicationDate = new DateTime(2022, 11, 8, 15, 43, 12, 369, DateTimeKind.Local).AddTicks(6876),
                            Title = "Graham, Schmeler and Renner"
                        },
                        new
                        {
                            Id = 65,
                            AuthorId = 65,
                            Genre = "Stage And Screen",
                            ISBN = "9874281405486",
                            Language = "Delaware",
                            PageCount = 8357,
                            PublicationDate = new DateTime(2023, 1, 10, 21, 33, 44, 685, DateTimeKind.Local).AddTicks(1576),
                            Title = "Blanda, Bode and Ullrich"
                        },
                        new
                        {
                            Id = 66,
                            AuthorId = 66,
                            Genre = "Funk",
                            ISBN = "4875435097491",
                            Language = "South Carolina",
                            PageCount = 5878,
                            PublicationDate = new DateTime(2022, 7, 14, 21, 8, 21, 901, DateTimeKind.Local).AddTicks(2266),
                            Title = "Trantow, White and Emmerich"
                        },
                        new
                        {
                            Id = 67,
                            AuthorId = 67,
                            Genre = "Blues",
                            ISBN = "9773514420220",
                            Language = "Sleek",
                            PageCount = 687,
                            PublicationDate = new DateTime(2022, 11, 24, 19, 22, 32, 410, DateTimeKind.Local).AddTicks(233),
                            Title = "Sawayn - Wuckert"
                        },
                        new
                        {
                            Id = 68,
                            AuthorId = 68,
                            Genre = "Electronic",
                            ISBN = "5080240986062",
                            Language = "lime",
                            PageCount = 3681,
                            PublicationDate = new DateTime(2022, 11, 4, 15, 5, 57, 906, DateTimeKind.Local).AddTicks(8061),
                            Title = "Hintz LLC"
                        },
                        new
                        {
                            Id = 69,
                            AuthorId = 69,
                            Genre = "Blues",
                            ISBN = "4740892936402",
                            Language = "Security",
                            PageCount = 7727,
                            PublicationDate = new DateTime(2022, 10, 5, 15, 54, 56, 698, DateTimeKind.Local).AddTicks(1357),
                            Title = "Metz LLC"
                        },
                        new
                        {
                            Id = 70,
                            AuthorId = 70,
                            Genre = "Soul",
                            ISBN = "1149036496353",
                            Language = "withdrawal",
                            PageCount = 1585,
                            PublicationDate = new DateTime(2023, 4, 16, 22, 39, 34, 211, DateTimeKind.Local).AddTicks(9390),
                            Title = "Cronin Group"
                        },
                        new
                        {
                            Id = 71,
                            AuthorId = 71,
                            Genre = "Classical",
                            ISBN = "0113923503081",
                            Language = "Innovative",
                            PageCount = 3025,
                            PublicationDate = new DateTime(2022, 12, 21, 12, 48, 37, 445, DateTimeKind.Local).AddTicks(4402),
                            Title = "Hills Group"
                        },
                        new
                        {
                            Id = 72,
                            AuthorId = 72,
                            Genre = "Electronic",
                            ISBN = "4576473011493",
                            Language = "communities",
                            PageCount = 2537,
                            PublicationDate = new DateTime(2022, 11, 1, 21, 48, 10, 982, DateTimeKind.Local).AddTicks(8708),
                            Title = "Jakubowski and Sons"
                        },
                        new
                        {
                            Id = 73,
                            AuthorId = 73,
                            Genre = "Rap",
                            ISBN = "8881564747783",
                            Language = "USB",
                            PageCount = 4654,
                            PublicationDate = new DateTime(2022, 10, 4, 2, 8, 24, 243, DateTimeKind.Local).AddTicks(4162),
                            Title = "West, Gutkowski and Mante"
                        },
                        new
                        {
                            Id = 74,
                            AuthorId = 74,
                            Genre = "Folk",
                            ISBN = "9139825520484",
                            Language = "National",
                            PageCount = 735,
                            PublicationDate = new DateTime(2023, 5, 25, 20, 53, 53, 679, DateTimeKind.Local).AddTicks(511),
                            Title = "Grant and Sons"
                        },
                        new
                        {
                            Id = 75,
                            AuthorId = 75,
                            Genre = "Blues",
                            ISBN = "2195335476069",
                            Language = "Pataca",
                            PageCount = 1500,
                            PublicationDate = new DateTime(2022, 9, 3, 0, 20, 32, 213, DateTimeKind.Local).AddTicks(916),
                            Title = "Rogahn - Schaefer"
                        },
                        new
                        {
                            Id = 76,
                            AuthorId = 76,
                            Genre = "World",
                            ISBN = "8448597927485",
                            Language = "Interactions",
                            PageCount = 3459,
                            PublicationDate = new DateTime(2023, 1, 30, 6, 52, 3, 9, DateTimeKind.Local).AddTicks(7469),
                            Title = "Treutel - Strosin"
                        },
                        new
                        {
                            Id = 77,
                            AuthorId = 77,
                            Genre = "Electronic",
                            ISBN = "2228869250499",
                            Language = "metrics",
                            PageCount = 6657,
                            PublicationDate = new DateTime(2022, 12, 6, 0, 23, 56, 663, DateTimeKind.Local).AddTicks(9749),
                            Title = "Schaden, Monahan and Predovic"
                        },
                        new
                        {
                            Id = 78,
                            AuthorId = 78,
                            Genre = "Soul",
                            ISBN = "4566293708857",
                            Language = "panel",
                            PageCount = 1803,
                            PublicationDate = new DateTime(2022, 9, 14, 8, 14, 17, 877, DateTimeKind.Local).AddTicks(702),
                            Title = "Zemlak - Kuvalis"
                        },
                        new
                        {
                            Id = 79,
                            AuthorId = 79,
                            Genre = "Classical",
                            ISBN = "8529985825443",
                            Language = "Bahrain",
                            PageCount = 3737,
                            PublicationDate = new DateTime(2022, 9, 11, 9, 1, 1, 746, DateTimeKind.Local).AddTicks(761),
                            Title = "Simonis, Effertz and Koss"
                        },
                        new
                        {
                            Id = 80,
                            AuthorId = 80,
                            Genre = "Hip Hop",
                            ISBN = "7948214038859",
                            Language = "Lead",
                            PageCount = 2298,
                            PublicationDate = new DateTime(2023, 7, 4, 2, 31, 2, 97, DateTimeKind.Local).AddTicks(9663),
                            Title = "Beier Inc"
                        },
                        new
                        {
                            Id = 81,
                            AuthorId = 81,
                            Genre = "Non Music",
                            ISBN = "8728938629330",
                            Language = "framework",
                            PageCount = 2847,
                            PublicationDate = new DateTime(2022, 8, 7, 16, 52, 29, 153, DateTimeKind.Local).AddTicks(5675),
                            Title = "Ruecker - Kris"
                        },
                        new
                        {
                            Id = 82,
                            AuthorId = 82,
                            Genre = "Jazz",
                            ISBN = "0053848008141",
                            Language = "Missouri",
                            PageCount = 5998,
                            PublicationDate = new DateTime(2023, 1, 24, 1, 11, 40, 551, DateTimeKind.Local).AddTicks(6948),
                            Title = "D'Amore, Moen and Simonis"
                        },
                        new
                        {
                            Id = 83,
                            AuthorId = 83,
                            Genre = "Jazz",
                            ISBN = "2418523165744",
                            Language = "indexing",
                            PageCount = 2172,
                            PublicationDate = new DateTime(2023, 1, 25, 12, 53, 47, 383, DateTimeKind.Local).AddTicks(8139),
                            Title = "McKenzie, Zulauf and Zemlak"
                        },
                        new
                        {
                            Id = 84,
                            AuthorId = 84,
                            Genre = "Classical",
                            ISBN = "5385929872606",
                            Language = "Rial Omani",
                            PageCount = 3083,
                            PublicationDate = new DateTime(2022, 12, 7, 11, 6, 10, 264, DateTimeKind.Local).AddTicks(8020),
                            Title = "Vandervort, Predovic and Stracke"
                        },
                        new
                        {
                            Id = 85,
                            AuthorId = 85,
                            Genre = "World",
                            ISBN = "4701884611424",
                            Language = "Handmade Steel Computer",
                            PageCount = 4773,
                            PublicationDate = new DateTime(2023, 4, 26, 23, 9, 21, 652, DateTimeKind.Local).AddTicks(1641),
                            Title = "Ryan - Ziemann"
                        },
                        new
                        {
                            Id = 86,
                            AuthorId = 86,
                            Genre = "Funk",
                            ISBN = "5293177636119",
                            Language = "matrix",
                            PageCount = 5871,
                            PublicationDate = new DateTime(2022, 11, 19, 3, 29, 0, 436, DateTimeKind.Local).AddTicks(5972),
                            Title = "Hand Inc"
                        },
                        new
                        {
                            Id = 87,
                            AuthorId = 87,
                            Genre = "Blues",
                            ISBN = "2218983210868",
                            Language = "regional",
                            PageCount = 4278,
                            PublicationDate = new DateTime(2022, 9, 26, 2, 59, 30, 965, DateTimeKind.Local).AddTicks(4885),
                            Title = "Schmidt - Dare"
                        },
                        new
                        {
                            Id = 88,
                            AuthorId = 88,
                            Genre = "Rap",
                            ISBN = "3347637828636",
                            Language = "Gorgeous Rubber Car",
                            PageCount = 7019,
                            PublicationDate = new DateTime(2023, 4, 23, 9, 32, 25, 829, DateTimeKind.Local).AddTicks(6492),
                            Title = "Hammes - Boehm"
                        },
                        new
                        {
                            Id = 89,
                            AuthorId = 89,
                            Genre = "Reggae",
                            ISBN = "0309745353328",
                            Language = "cohesive",
                            PageCount = 3585,
                            PublicationDate = new DateTime(2023, 5, 23, 4, 3, 54, 643, DateTimeKind.Local).AddTicks(7537),
                            Title = "Stoltenberg, Kuhic and Ullrich"
                        },
                        new
                        {
                            Id = 90,
                            AuthorId = 90,
                            Genre = "Hip Hop",
                            ISBN = "6002379349050",
                            Language = "Unbranded Fresh Car",
                            PageCount = 5630,
                            PublicationDate = new DateTime(2023, 6, 1, 20, 18, 41, 345, DateTimeKind.Local).AddTicks(4264),
                            Title = "Conn, Lemke and Keebler"
                        },
                        new
                        {
                            Id = 91,
                            AuthorId = 91,
                            Genre = "Electronic",
                            ISBN = "4527669005369",
                            Language = "Program",
                            PageCount = 2903,
                            PublicationDate = new DateTime(2023, 4, 3, 5, 24, 34, 569, DateTimeKind.Local).AddTicks(8138),
                            Title = "Hammes and Sons"
                        },
                        new
                        {
                            Id = 92,
                            AuthorId = 92,
                            Genre = "Jazz",
                            ISBN = "3879695395251",
                            Language = "program",
                            PageCount = 2849,
                            PublicationDate = new DateTime(2022, 10, 8, 3, 21, 28, 314, DateTimeKind.Local).AddTicks(309),
                            Title = "Yost - Hahn"
                        },
                        new
                        {
                            Id = 93,
                            AuthorId = 93,
                            Genre = "Latin",
                            ISBN = "6340258017530",
                            Language = "Clothing",
                            PageCount = 3880,
                            PublicationDate = new DateTime(2023, 1, 21, 9, 43, 9, 417, DateTimeKind.Local).AddTicks(4182),
                            Title = "Langworth and Sons"
                        },
                        new
                        {
                            Id = 94,
                            AuthorId = 94,
                            Genre = "Soul",
                            ISBN = "8902974037582",
                            Language = "array",
                            PageCount = 4729,
                            PublicationDate = new DateTime(2023, 1, 11, 4, 33, 51, 725, DateTimeKind.Local).AddTicks(6266),
                            Title = "Luettgen, Kovacek and Mante"
                        },
                        new
                        {
                            Id = 95,
                            AuthorId = 95,
                            Genre = "Folk",
                            ISBN = "2400117416479",
                            Language = "Landing",
                            PageCount = 561,
                            PublicationDate = new DateTime(2022, 11, 28, 5, 58, 51, 576, DateTimeKind.Local).AddTicks(1287),
                            Title = "Cremin - Abbott"
                        },
                        new
                        {
                            Id = 96,
                            AuthorId = 96,
                            Genre = "Blues",
                            ISBN = "9044968505871",
                            Language = "Persistent",
                            PageCount = 5190,
                            PublicationDate = new DateTime(2023, 1, 31, 11, 7, 52, 617, DateTimeKind.Local).AddTicks(2656),
                            Title = "Ward Group"
                        },
                        new
                        {
                            Id = 97,
                            AuthorId = 97,
                            Genre = "Metal",
                            ISBN = "6098011764367",
                            Language = "Practical Granite Towels",
                            PageCount = 3372,
                            PublicationDate = new DateTime(2022, 7, 17, 13, 55, 13, 574, DateTimeKind.Local).AddTicks(8438),
                            Title = "Kerluke - Renner"
                        },
                        new
                        {
                            Id = 98,
                            AuthorId = 98,
                            Genre = "World",
                            ISBN = "3358325895984",
                            Language = "Islands",
                            PageCount = 9145,
                            PublicationDate = new DateTime(2022, 12, 20, 22, 13, 27, 384, DateTimeKind.Local).AddTicks(830),
                            Title = "Kub Inc"
                        },
                        new
                        {
                            Id = 99,
                            AuthorId = 99,
                            Genre = "Electronic",
                            ISBN = "2705952741701",
                            Language = "Outdoors & Automotive",
                            PageCount = 7785,
                            PublicationDate = new DateTime(2022, 12, 4, 3, 53, 21, 496, DateTimeKind.Local).AddTicks(475),
                            Title = "Purdy, Deckow and Yost"
                        });
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Janis",
                            SurName = "Hermann"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tanya",
                            SurName = "Hartmann"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Kenny",
                            SurName = "Okuneva"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ken",
                            SurName = "Koch"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kerry",
                            SurName = "Brekke"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ida",
                            SurName = "Torp"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Candace",
                            SurName = "Heller"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Veronica",
                            SurName = "Schmitt"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Debbie",
                            SurName = "Kessler"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Wallace",
                            SurName = "Deckow"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kimberly",
                            SurName = "Wiza"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Cesar",
                            SurName = "Schinner"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ebony",
                            SurName = "Gislason"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mindy",
                            SurName = "Bergstrom"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Carrie",
                            SurName = "Gorczany"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Maxine",
                            SurName = "Kshlerin"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Crystal",
                            SurName = "Durgan"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Denise",
                            SurName = "Waters"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Roger",
                            SurName = "Simonis"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Nina",
                            SurName = "Littel"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Corey",
                            SurName = "Schultz"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tim",
                            SurName = "Fay"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Dave",
                            SurName = "O'Reilly"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Matt",
                            SurName = "Spinka"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Jean",
                            SurName = "Kunze"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Loren",
                            SurName = "Crist"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Stephanie",
                            SurName = "Armstrong"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Timmy",
                            SurName = "Halvorson"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Tami",
                            SurName = "Reilly"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Lynn",
                            SurName = "Keebler"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Lindsey",
                            SurName = "Toy"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Maxine",
                            SurName = "Hermiston"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Jonathan",
                            SurName = "Jacobs"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Enrique",
                            SurName = "Bartoletti"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Ismael",
                            SurName = "Herzog"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Donald",
                            SurName = "Hartmann"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Erma",
                            SurName = "Hane"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Karla",
                            SurName = "Kutch"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Matt",
                            SurName = "Mertz"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Lewis",
                            SurName = "Schiller"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Lamar",
                            SurName = "Koch"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Nora",
                            SurName = "Lindgren"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Tammy",
                            SurName = "Graham"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Jeannie",
                            SurName = "Baumbach"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Peter",
                            SurName = "Ledner"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Don",
                            SurName = "Waelchi"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Jamie",
                            SurName = "Turcotte"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Derrick",
                            SurName = "Jenkins"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Freddie",
                            SurName = "Adams"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Kristen",
                            SurName = "Roob"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Becky",
                            SurName = "Stamm"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Frank",
                            SurName = "Johnston"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Joy",
                            SurName = "Beahan"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Eduardo",
                            SurName = "Nitzsche"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Jason",
                            SurName = "Predovic"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Rufus",
                            SurName = "Bradtke"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Lawrence",
                            SurName = "Hauck"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Olivia",
                            SurName = "Bruen"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Cedric",
                            SurName = "Yost"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Jimmie",
                            SurName = "Vandervort"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Camille",
                            SurName = "Bergnaum"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Lee",
                            SurName = "Kris"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Diane",
                            SurName = "Witting"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Daisy",
                            SurName = "Graham"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Wallace",
                            SurName = "Rohan"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Mandy",
                            SurName = "Powlowski"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Jody",
                            SurName = "Stehr"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Carlton",
                            SurName = "Kutch"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Jennie",
                            SurName = "Miller"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Jessie",
                            SurName = "Powlowski"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Domingo",
                            SurName = "Raynor"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Johnnie",
                            SurName = "O'Conner"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Tracy",
                            SurName = "Beer"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Nellie",
                            SurName = "Sawayn"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Ernest",
                            SurName = "Grady"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Della",
                            SurName = "Jones"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Constance",
                            SurName = "Flatley"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Terry",
                            SurName = "Greenfelder"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Bertha",
                            SurName = "Schneider"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Tracy",
                            SurName = "Wolf"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Della",
                            SurName = "Douglas"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Jesse",
                            SurName = "Dicki"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Greg",
                            SurName = "Greenholt"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Hattie",
                            SurName = "Kiehn"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Levi",
                            SurName = "Beier"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Leslie",
                            SurName = "Pagac"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Lawrence",
                            SurName = "Bailey"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Bernadette",
                            SurName = "Olson"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Sheri",
                            SurName = "Heller"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Wanda",
                            SurName = "Tillman"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Suzanne",
                            SurName = "Kulas"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Claire",
                            SurName = "Lehner"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Shawn",
                            SurName = "Kerluke"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Norma",
                            SurName = "Witting"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lauren",
                            SurName = "Murazik"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Elaine",
                            SurName = "Adams"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Nichole",
                            SurName = "Bruen"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Jeanette",
                            SurName = "Corwin"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Marshall",
                            SurName = "Abshire"
                        });
                });

            modelBuilder.Entity("HotChocolate.Checker.Persistence.Entities.BookEntity", b =>
                {
                    b.HasOne("HotChocolate.Checker.Persistence.Entities.UserEntity", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
