version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql